Algoritmo "exemplosimples"
// Disciplina   :  Lógica de Programação em js
// Professor   : Jailson
// Descrição   : programa simples
// Autor(a)    : Stefany
// Data atual  : 05/09/2024
Var
// Seção de Declarações das variáveis
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Informe um numero :")
leia (numero)
se numero > 100 entao
escreval (" O numero é maior que 100")
fimse

Fimalgoritmo